"""changes in User table

Revision ID: f98f7ba6e26e
Revises: e3913335b0f6
Create Date: 2023-04-27 22:05:10.571092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98f7ba6e26e'
down_revision = 'e3913335b0f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
